"""Remove post_id from Reply model, update relationships

Revision ID: 84125a4a720c
Revises: 04d9b1e4789e
Create Date: 2025-10-03 17:53:36.359065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84125a4a720c'
down_revision = '04d9b1e4789e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('replies_post_id_fkey'), type_='foreignkey')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('replies_post_id_fkey'), 'posts', ['post_id'], ['id'])

    # ### end Alembic commands ###
