from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a822313e6e70'
down_revision = '8c5e3fe63cf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            'fk_reply_comment_id',  # Add a constraint name
            'comments', ['comment_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reply_comment_id', type_='foreignkey')
        batch_op.drop_column('comment_id')

    # ### end Alembic commands ###