"""Initial schema for Blogpost App

Revision ID: c8180c055a50
Revises: b225c1131b5d
Create Date: 2025-08-26 15:41:57.881416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8180c055a50'
down_revision = 'b225c1131b5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured_image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('featured_image')

    # ### end Alembic commands ###
