"""Add excerpt to Post

Revision ID: de3d2aba75d2
Revises: 9c7d6d2b7c11
Create Date: 2025-09-06 15:47:49.167703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de3d2aba75d2'
down_revision = '9c7d6d2b7c11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('excerpt', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('excerpt')

    # ### end Alembic commands ###
